### PR TITLE
feat: Update the GH repo

### PR DESCRIPTION
**Pull request by ZPascal**
**Description:**
The PR adjusts the GH action.

**Tasks:**

- Update the GH action

**Recommendation:**
- Clean up the repository and remove the `venv` folder, as it is not recommended to check in its virtual environment and it's not so easy to contribute to the project.

### CODE REVIEW

**Review by matteemol — APPROVED** [review]
Thanks!

**Comment by matteemol** [comment]
Regarding the ``venv`` folder, I would rather prefer to keep it in the repository for a while.
As you can see, this is the first PR that I'm facing to, so it'll take some time to accept it (I'm trying to accept the first commit only).

**Review by matteemol — CHANGES_REQUESTED** [review]
I would prefer to keep the ``venv`` for now, but not sure how to merge only the first commit without breaking everything. Could you change the PR to just modifying the  actions file, please?

**Comment by ZPascal** [comment]
> Regarding the `venv` folder, I would rather prefer to keep it in the repository for a while. As you can see, this is the first PR that I'm facing to, so it'll take some time to accept it (I'm trying to accept the first commit only).

You should remove the `venv` as soon as possible, as no one can [simply contribute](https://stackoverflow.com/a/6590783/8574911) to the repository. You are using a hard pinned version and for example, on Linux, I must remove the folder completely to set up an environment! All steps should be linked e.g. in the requierments.txt file and if you need the environment without an internet connection you should think of using the `vendor` [folder](https://medium.com/underdog-io-engineering/vendoring-python-dependencies-with-pip-b9eb6078b9c0).

**Comment by ZPascal** [comment]
> I would prefer to keep the `venv` for now, but not sure how to merge only the first commit without breaking everything. Could you change the PR to just modifying the actions file, please?

I have reverted the commit. As described [here](https://github.com/matteemol/dbSketcher/pull/1#issuecomment-2041954351), you should clean up the repository and remove the `venv` folder.

**Review by matteemol — APPROVED** [review]

**Pull request merged**
